name: C/C++ CI

on:
  push:
    branches:
      - master
      - dashing-devel
  pull_request:
    branches:
      - master
      - dashing-devel

jobs:
  build:
    runs-on: ubuntu-latest
    container: ros:eloquent-ros-core-bionic
    steps:
    - uses: actions/checkout@v2
    - name: install_dependencies
      run: |
        apt-get update
        apt-get install libyaml-cpp-dev -y
        apt-get install ros-eloquent-camera-info-manager -y
    - name: build
      run: colcon build
    - name: test
      run: colcon test
    - name: test results
      run: colcon test-results
